project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - intro.qmd
    - summary.qmd

website:
  title: ""
  navbar: false
  sidebar: false

format:
  html:
    theme: none
    css: estilos.css
    self-contained: true
